# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  version:  # id of input
    description: 'gRPC client version'
    required: true
runs:
  using: 'docker'
  image: 'docker://kjconroy/gengengen'
